FROM python:3.7.3-alpine3.9

MAINTAINER Richard Dally "r.dally@protonmail.com"

ARG GITHUB_PROJECT

COPY $GITHUB_PROJECT/requirements.txt /

RUN pip3 install pytest-cov pytest
RUN pip3 install -r requirements.txt

WORKDIR /opt/$GITHUB_PROJECT
COPY $GITHUB_PROJECT/*.py /opt/$GITHUB_PROJECT/
COPY pytest.ini /

ENTRYPOINT ["python3", "-m", "pytest", "--cov-report", "xml:/coverage/"]
